### ISSUE TITLE
Does the Blender dataset class support depth rank loss?

### ISSUE THREAD

**Issue by hermosaaurora** [Wanggcong/FreeNeRF_plus_SparseNeRF#1]
I didn't find where to load the depth images in your code:

https://github.com/Wanggcong/FreeNeRF_plus_SparseNeRF/blob/63e0eaa2f8a71f3571235c083cedb91b65cd2989/internal/datasets_depth.py#L974-L1045

And your example config files are about DTU and LLFF.

**Comment by hermosaaurora** [comment]
Besides, in your repo for [sparsenerf](https://github.com/Wanggcong/SparseNeRF), it seems that there is no Blender dataset class. But I think it may help a lot if we want to apply the method to custom dataset created by Blender.

**Comment by Wanggcong** [comment]
Thank you for your question. Since most of the few-shot nerf methods does not conduct experiments on the Blender dataset, we did not conduct experiments on this dataset. I think it should work on this dataset since we have done on 5 datasets and it it easy to make it work.

Well, we might not directly provide code for this dataset, but we would like to share how to implement SparseNeRF on general custom datasets as described in the features of SparseNeRF in a few coming days (a tutorial).

**Comment by Wanggcong** [comment]
Hi, I write a rough tutorial in this [link](https://github.com/Wanggcong/SparseNeRF/blob/main/tutorial.md). Please let me know if it can solve your problem.

**Comment by Wanggcong** [comment]
I closed this issue since it is also discussed in [this issue](https://github.com/Wanggcong/SparseNeRF/issues/6) of sparesenerf.
